pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - or:
        - approved-reviews-by>=1
        - author=github-actions[bot]
    actions:
      merge:
        method: merge
