name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  issues:
    types: [opened]
  push:
    branches:
      - main

jobs:
  test-chuch: # make sure the action works on a clean machine without building
    if: github.event_name == 'pull_request' || github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Add funny comment
      - uses: actions/checkout@v2
      - id: FunnyComment
        uses: Marta83/funny-comment-action@v2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'all'
